device : cuda
model_name : AFCF3D
dataset_name : MNCD256
data_type : HG #cloud is another option
dataset_path : HZDR-FWGEL/MineNetCD256
input_nc : 3
num_classes : 2
push_to_hub : False

train:
  epochs : 100
  batch_size : 32
  lr : 0.0001
  loss: BCE
  snapshots_dir : ./checkpoints/
  optim : Adam
  save_intervals : 10
eval :
  batch_size : 32
test:
  batch_size : 32
  checkpoint : checkpoints/GVLM256/DMINet/"epoch 99/pytorch_model.bin
  save_path : ./results/
