device : cuda
model_name : BIT
dataset_name : LEVIRCD256
data_type : local #HG is another option
dataset_path : /private/icme_cd/UCD/data/LEVIR-CD-HF
input_nc : 3
num_classes : 2
push_to_hub : False

train:
  epochs : 100
  batch_size : 16
  lr : 0.0001
  loss: CrossEntropy
  snapshots_dir : ./results/checkpoints/
  optim : Adam
  save_intervals : 1
eval :
  batch_size : 32
test:
  batch_size : 32
  checkpoint : checkpoints/GVLM256/DMINet/"epoch 99/pytorch_model.bin
  save_path : ./results/
