device : cuda
model_name : SiamUnet_diff
dataset_name : EGY_BCD
data_type : HG #HG is another option
dataset_path : ericyu/EGY_BCD
input_nc : 3
num_classes : 2
push_to_hub : False

train:
  epochs : 100
  batch_size : 32
  lr : 0.0001
  loss: CrossEntropy
  snapshots_dir : ./checkpoints/
  optim : Adam
  save_intervals : 10
eval :
  batch_size : 32
test:
  batch_size : 32
  checkpoint : checkpoints/GVLM256/DMINet/"epoch 99/pytorch_model.bin
  save_path : ./results/
